jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Grant execute permission
        run: chmod +x script/bootstrap
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
